import { Inter } from "next/font/google"
import Link from "next/link"
import { Navigation } from "./ui/Navigation"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const links: Array<{ href: string; key: string }> = [
  {
    href: "/",
    key: "home",
  },
  {
    href: "/dashboard",
    key: "dashboard",
  },
  {
    href: "/guides",
    key: "guides",
  },

  {
    href: "/login",
    key: "login",
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div style={{ color: "orange" }}>/app/layout.tsx 적용</div> */}
        <header>
          <div>
            <Navigation links={links} />

            {/* <ul className="flex bg-slate-500">
              {links.map(({ href, key }) => (
                <li key={key} className="flex-auto">
                  <Link href={href}>{key}</Link>
                </li>
              ))}
            </ul> */}
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
